#!/usr/bin/env bash
# Deterministic scenario generator for the TuiStreamSpec DRT gate
# (the `lean-verify` op=drt input_gen for the lean/TuiStreamDrt.lean vs
# bin/tui-stream-drt pair; docs/tui-streaming-response.md "Verification").
#
# Emits N well-formed one-line scenarios of the shared protocol:
#   FT SC DRAFT SETTLED RESPONSES
#
# Determinism: a fixed-seed Park-Miller LCG (no external randomness, no
# $RANDOM), so any two runs agree line for line and a re-run of the
# gate reproduces its inputs exactly.
#
# Domain: the chunk-text alphabet is the ASCII letters a-j and digits
# 0-9, so the byte value of a character equals its code on both sides
# of the gate (the Lean side's charVal table maps it directly); the
# text-token encoding `<n>:<hex>` then needs no ambiguity resolution.
#
# Usage: scripts/tui-stream-drt-inputs.sh [N]   (default N=100000)
set -euo pipefail
n="${1:-100000}"
awk -v n="$n" '
BEGIN {
  # DRT chunk alphabet -> byte values, in hex:
  #   a b c d e f g h i j 0 1 2 3 4 5 6 7 8 9
  split("61 62 63 64 65 66 67 68 69 6a 30 31 32 33 34 35 36 37 38 39", H, " ")
  st = 123456789
  for (i = 0; i < n; i++) {
    ft = r(2)
    sc = r(64)
    d = tok(r(4))                      # draft text
    sk = r(3)                          # settled count (0..2)
    if (sk == 0) { sf = "0" }
    else {
      sf = sk
      for (j = 1; j <= sk; j++) sf = sf "," tok(r(3))
    }
    rm = r(4)                          # response count (0..3)
    if (rm == 0) { rf = "0" }
    else {
      rf = rm
      for (j = 1; j <= rm; j++) {
        c = r(5)                       # chunks in this response (0..4)
        rf = rf "," c
        for (k = 1; k <= c; k++) rf = rf "," tok(r(2))
      }
    }
    printf "%d %d %s %s %s\n", ft, sc, d, sf, rf
  }
}
# Park-Miller LCG, period 2^31-1; exact under IEEE-754 doubles.
function r(m) { st = (st * 48271) % 2147483647; return int(st / 2147483647 * m) }
# A <len>-character text token: <len>:<hex of the generated bytes>.
function tok(len,  i, s, idx) {
  s = ""
  for (i = 0; i < len; i++) { idx = r(20) + 1; s = s H[idx] }
  return len ":" s
}
'
